site_name: "LangChain-OpenTutorial"
site_description: Build reliable, stateful AI systems, without giving up control
site_url: https://www.xiaoshun.info/mkdoc/
repo_url: https://github.com/xiaoshun007/mkdoc
